# Generated by Django 6.0.1 on 2026-01-10 22:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('proprietaire', 'Propriétaire'), ('responsable_location', 'Responsable Location'), ('responsable_financier', 'Responsable Financier'), ('client', 'Client'), ('visiteur', 'Visiteur')], default='visiteur', max_length=50)),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('forfait_agence', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Forfait agence')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion_immobiliere.profile')),
                ('numero_fiscal', models.CharField(max_length=50, unique=True, verbose_name='Numéro fiscal')),
                ('rib', models.CharField(blank=True, max_length=50, null=True, verbose_name='RIB')),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
    ]
