# Generated by Django 6.0.1 on 2026-01-10 23:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion_immobiliere.profile')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('employeur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employeur')),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenu mensuel (€)')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AlterField(
            model_name='zone',
            name='forfait_agence',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Forfait agence (€)'),
        ),
        migrations.CreateModel(
            name='ContratGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant mensuel propriétaire (€)')),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('en_attente', 'En attente de signature')], default='en_attente', max_length=20, verbose_name='État du contrat')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='Date de signature')),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats_gestion/', verbose_name='Contrat signé')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_gestion', to='gestion_immobiliere.proprietaire', verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Contrat de gestion',
                'verbose_name_plural': 'Contrats de gestion',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_logement', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('studio', 'Studio'), ('immeuble', 'Immeuble')], max_length=20, verbose_name='Type de logement')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface (m²)')),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('maintenance', 'En maintenance'), ('archive', 'Archivé')], default='disponible', max_length=20, verbose_name='État')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('caution_fixe', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Caution (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to='gestion_immobiliere.proprietaire', verbose_name='Propriétaire')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='gestion_immobiliere.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Logement',
                'verbose_name_plural': 'Logements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/', verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_immobiliere.logement')),
            ],
            options={
                'verbose_name': 'Image de logement',
                'verbose_name_plural': 'Images de logement',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DemandeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_debut_souhaitee', models.DateField(verbose_name='Date de début souhaitée')),
                ('duree_souhaitee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Durée souhaitée (mois)')),
                ('etat', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée'), ('convertie', 'Convertie en contrat')], default='attente', max_length=20, verbose_name='État de la demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to='gestion_immobiliere.client', verbose_name='Client')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to='gestion_immobiliere.logement', verbose_name='Logement')),
            ],
            options={
                'verbose_name': 'Demande de location',
                'verbose_name_plural': 'Demandes de location',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant du loyer (FCFA)')),
                ('caution_versee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Caution versée (FCFA))')),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('resilie', 'Résilié'), ('en_attente', 'En attente de signature')], default='en_attente', max_length=20, verbose_name='État du contrat')),
                ('date_signature', models.DateTimeField(auto_now_add=True, verbose_name='Date de signature')),
                ('contrat_signe', models.FileField(blank=True, null=True, upload_to='contrats_location/', verbose_name='Contrat signé')),
                ('bulletin_salaire', models.FileField(blank=True, null=True, upload_to='documents_clients/', verbose_name='Bulletin de salaire')),
                ('casier_judiciaire', models.FileField(blank=True, null=True, upload_to='documents_clients/', verbose_name='Casier judiciaire')),
                ('carte_identite', models.FileField(blank=True, null=True, upload_to='documents_clients/', verbose_name="Carte d'identité")),
                ('garant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du garant')),
                ('telephone_garant', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du garant')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_location', to='gestion_immobiliere.client', verbose_name='Client')),
                ('contrat_gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_location', to='gestion_immobiliere.contratgestion', verbose_name='Contrat de gestion')),
                ('demande_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_location', to='gestion_immobiliere.demandelocation', verbose_name='Demande de location')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_location', to='gestion_immobiliere.logement', verbose_name='Logement')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'verbose_name_plural': 'Contrats de location',
                'ordering': ['-date_signature'],
            },
        ),
        migrations.AddField(
            model_name='contratgestion',
            name='logement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_gestion', to='gestion_immobiliere.logement', verbose_name='Logement'),
        ),
        migrations.CreateModel(
            name='PaiementLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois concerné')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (€)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_limite', models.DateField(verbose_name='Date limite de paiement')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_retard', 'En retard'), ('impaye', 'Impayé'), ('partiel', 'Paiement partiel')], default='impaye', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence du paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('contrat_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_immobiliere.contratlocation', verbose_name='Contrat de location')),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Encaisse par')),
            ],
            options={
                'verbose_name': 'Paiement de loyer',
                'verbose_name_plural': 'Paiements de loyer',
                'ordering': ['-mois'],
            },
        ),
        migrations.CreateModel(
            name='PaiementProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois concerné')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (€)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_limite', models.DateField(verbose_name='Date limite de paiement')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_retard', 'En retard'), ('impaye', 'Impayé'), ('partiel', 'Paiement partiel')], default='impaye', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=20, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contrat_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_proprietaire', to='gestion_immobiliere.contratgestion', verbose_name='Contrat de gestion')),
            ],
            options={
                'verbose_name': 'Paiement propriétaire',
                'verbose_name_plural': 'Paiements propriétaires',
                'ordering': ['-mois'],
            },
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['reference'], name='gestion_imm_referen_03a804_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['etat'], name='gestion_imm_etat_433774_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['type_logement'], name='gestion_imm_type_lo_f63125_idx'),
        ),
        migrations.AddIndex(
            model_name='demandelocation',
            index=models.Index(fields=['etat'], name='gestion_imm_etat_49251f_idx'),
        ),
        migrations.AddIndex(
            model_name='demandelocation',
            index=models.Index(fields=['date_demande'], name='gestion_imm_date_de_12f7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contratlocation',
            index=models.Index(fields=['etat'], name='gestion_imm_etat_5fb7db_idx'),
        ),
        migrations.AddIndex(
            model_name='contratlocation',
            index=models.Index(fields=['date_debut', 'date_fin'], name='gestion_imm_date_de_4a6e27_idx'),
        ),
        migrations.AddIndex(
            model_name='contratgestion',
            index=models.Index(fields=['etat'], name='gestion_imm_etat_71ab15_idx'),
        ),
        migrations.AddIndex(
            model_name='contratgestion',
            index=models.Index(fields=['date_debut', 'date_fin'], name='gestion_imm_date_de_31249a_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementloyer',
            index=models.Index(fields=['statut'], name='gestion_imm_statut_30ccc2_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementloyer',
            index=models.Index(fields=['date_limite'], name='gestion_imm_date_li_89cc2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paiementloyer',
            unique_together={('contrat_location', 'mois')},
        ),
        migrations.AlterUniqueTogether(
            name='paiementproprietaire',
            unique_together={('contrat_gestion', 'mois')},
        ),
    ]
