# Generated by Django 6.0.1 on 2026-01-12 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0002_client_alter_zone_forfait_agence_contratgestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateTimeField(verbose_name='Date et heure du rendez-vous')),
                ('duree_estimee', models.IntegerField(default=60, verbose_name='Durée estimée (minutes)')),
                ('lieu', models.TextField(verbose_name='Lieu de rendez-vous')),
                ('contact_client', models.CharField(max_length=20, verbose_name='Téléphone client')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('effectue', 'Effectué'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contact_agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_animes', to=settings.AUTH_USER_MODEL, verbose_name='Contact agence')),
                ('demande_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='gestion_immobiliere.demandelocation', verbose_name='Demande de location')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rendez_vous'],
            },
        ),
    ]
