# Generated by Django 6.0.1 on 2026-02-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0003_rendezvous'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contratlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('etat', 'en_cours')), fields=('logement',), name='unique_logement_contrat_location_en_cours'),
        ),
    ]
