# Generated by Django 4.2.28 on 2026-02-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobiliere', '0004_contratlocation_unique_logement_contrat_location_en_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratgestion',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_gestion', to='gestion_immobiliere.logement', verbose_name='Logement'),
        ),
        migrations.AddConstraint(
            model_name='contratgestion',
            constraint=models.UniqueConstraint(condition=models.Q(('etat', 'en_cours')), fields=('logement',), name='unique_contrat_gestion_en_cours_par_logement'),
        ),
    ]
